# Generated by Django 5.0.7 on 2024-07-30 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('gmail', models.EmailField(max_length=50)),
                ('created_at', models.DateField(verbose_name=datetime.datetime(2024, 7, 30, 12, 30, 56, 225332))),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
