# Generated by Django 5.0.7 on 2024-07-30 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 7, 30, 12, 43, 59, 556454)),
        ),
    ]
